Fixing repo main update action

diff --git a/.github/workflows/update_index.yml b/.github/workflows/update_index.yml
--- a/.github/workflows/update_index.yml
+++ b/.github/workflows/update_index.yml
@@ -21,12 +21,12 @@ jobs:
         run: pip install requests
 
       - name: Run Script
-        run: python your_script_name.py
+        run: python main.py
 
       - name: Commit and Push
         run: |
-          git config --local user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
-          git add minecraft_mirrored_index.md
+          git add README.md
           git commit -m "Auto-update Minecraft Index" || echo "No changes to commit"
-          git push
+          git push || { echo "Push failed"; exit 1; }
